<a href="https://colab.research.google.com/github/kmoreno7/deep-learning-challenge/blob/main/AlphabetSoupCharity_Optimization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

In [3]:
from google.colab import files
uploaded = files.upload()

Saving charity_data.csv to charity_data.csv

In [4]:
import io
df = pd.read_csv(io.BytesIO(uploaded['charity_data.csv']))
# Dataset is now stored in a Pandas Dataframe

In [5]:
#Turn csv into a pandas dataframe
file = "charity_data.csv"

In [6]:
application_df = pd.read_csv(file)
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [7]:
# Drop the non-beneficial ID columns, 'EIN' and 'STATUS'.
new_app_df = application_df.drop(columns=['EIN'])
new_app_df

,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...,...
34294,THE LIONS CLUB OF HONOLULU KAMEHAMEHA,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,INTERNATIONAL ASSOCIATION OF LIONS CLUBS,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,PTA HAWAII CONGRESS,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,AMERICAN FEDERATION OF GOVERNMENT EMPLOYEES LO...,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,WATERHOUSE CHARITABLE TR,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [8]:
# Determine the number of unique values in each column.
for x in application_df.columns:
    print(x, len(application_df[x].unique()))

EIN 34299
NAME 19568
APPLICATION_TYPE 17
AFFILIATION 6
CLASSIFICATION 71
USE_CASE 5
ORGANIZATION 4
STATUS 2
INCOME_AMT 9
SPECIAL_CONSIDERATIONS 2
ASK_AMT 8747
IS_SUCCESSFUL 2

In [9]:
# Look at APPLICATION_TYPE value counts for binning
count = new_app_df['APPLICATION_TYPE'].value_counts()
count

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [10]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(count[count<500].index)
application_types_to_replace

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [11]:
# Look at CLASSIFICATION value counts for binning
countsbinning = application_df['CLASSIFICATION'].value_counts()
countsbinning

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [12]:
# You may find it helpful to look at CLASSIFICATION value counts >1
countsclassification = countsbinning[countsbinning>1]
countsclassification

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [13]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list (countsbinning[countsbinning<100].index)
classifications_to_replace

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      669
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Name: CLASSIFICATION, dtype: int64

In [14]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df,dtype=float)
application_df.head()

,EIN,STATUS,ASK_AMT,IS_SUCCESSFUL,NAME_1 DAY RANCH RESCUE AND RURAL OKLAHOMA ANIMAL RESOURCE INC,NAME_100 BLACK MEN OF AMERICA,NAME_100 BLACK MEN OF MEMPHIS INC,NAME_100 BLACK MEN OF WEST GEORGIA INC,NAME_1150 WEBSTER STREET INC,NAME_116TH CAVALRY REGIMENT CHAPTER OF THE US CAVALRY & ARMOR ASSOCIATION,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,10520599,1,5000,1,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,10531628,1,108590,1,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,10547893,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,10553066,1,6692,1,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,10556103,1,142590,1,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [15]:
# Split our preprocessed data into our features and target arrays
y = application_df['IS_SUCCESSFUL'].values
y

# Take out IS_SUCCESSFUL
X = application_df.drop('IS_SUCCESSFUL', axis=1).values
X

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state = 42)

In [16]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [17]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len( X_train_scaled[0])
hidden_nodes_layer1=7
hidden_nodes_layer2=14
hidden_nodes_layer3=21

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation='relu'))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 7)                 137333

 dense_1 (Dense)             (None, 14)                112

 dense_2 (Dense)             (None, 1)                 15

=================================================================
Total params: 137,460
Trainable params: 137,460
Non-trainable params: 0
_________________________________________________________________

In [18]:
# Compile the model
nn.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])

In [19]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,validation_split=0.15, epochs=100)

Epoch 1/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5868 - accuracy: 0.6849 - val_loss: 0.4515 - val_accuracy: 0.7865
Epoch 2/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4230 - accuracy: 0.7955 - val_loss: 0.4443 - val_accuracy: 0.7940
Epoch 3/100
684/684 [==============================] - 2s 3ms/step - loss: 0.2846 - accuracy: 0.8555 - val_loss: 0.6739 - val_accuracy: 0.7999
Epoch 4/100
684/684 [==============================] - 2s 3ms/step - loss: 0.1683 - accuracy: 0.9353 - val_loss: 1.1333 - val_accuracy: 0.7976
Epoch 5/100
684/684 [==============================] - 2s 3ms/step - loss: 0.1265 - accuracy: 0.9505 - val_loss: 1.5062 - val_accuracy: 0.7914
Epoch 6/100
684/684 [==============================] - 2s 3ms/step - loss: 0.1149 - accuracy: 0.9532 - val_loss: 1.7448 - val_accuracy: 0.7927
Epoch 7/100
684/684 [==============================] - 2s 3ms/step - loss: 0.1098 - accuracy: 0.9551 - val_loss: 1.8360 - val_accuracy: 0.7974
Epoch 8/100
684/684 [==============================] - 2s 3ms/step - loss: 0.1064 - accuracy: 0.9559 - val_loss: 1.8991 - val_accuracy: 0.8020
Epoch 9/100
684/684 [==============================] - 2s 3ms/step - loss: 0.1043 - accuracy: 0.9559 - val_loss: 1.9929 - val_accuracy: 0.7981
Epoch 10/100
684/684 [==============================] - 2s 3ms/step - loss: 0.1026 - accuracy: 0.9577 - val_loss: 2.0030 - val_accuracy: 0.8007
Epoch 11/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0999 - accuracy: 0.9592 - val_loss: 2.0786 - val_accuracy: 0.7997
Epoch 12/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0995 - accuracy: 0.9602 - val_loss: 1.9881 - val_accuracy: 0.7992
Epoch 13/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0965 - accuracy: 0.9614 - val_loss: 1.9989 - val_accuracy: 0.8015
Epoch 14/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0957 - accuracy: 0.9610 - val_loss: 2.0152 - val_accuracy: 0.7979
Epoch 15/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0946 - accuracy: 0.9614 - val_loss: 1.9698 - val_accuracy: 0.8020
Epoch 16/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0933 - accuracy: 0.9626 - val_loss: 1.8869 - val_accuracy: 0.8010
Epoch 17/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0929 - accuracy: 0.9625 - val_loss: 1.8329 - val_accuracy: 0.8002
Epoch 18/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0929 - accuracy: 0.9632 - val_loss: 1.7809 - val_accuracy: 0.8007
Epoch 19/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0922 - accuracy: 0.9623 - val_loss: 1.8553 - val_accuracy: 0.8005
Epoch 20/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0918 - accuracy: 0.9635 - val_loss: 1.7631 - val_accuracy: 0.7997
Epoch 21/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0919 - accuracy: 0.9629 - val_loss: 1.7862 - val_accuracy: 0.8012
Epoch 22/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0909 - accuracy: 0.9637 - val_loss: 1.7668 - val_accuracy: 0.7994
Epoch 23/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0903 - accuracy: 0.9630 - val_loss: 1.6549 - val_accuracy: 0.8007
Epoch 24/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0901 - accuracy: 0.9634 - val_loss: 1.7068 - val_accuracy: 0.8005
Epoch 25/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0899 - accuracy: 0.9636 - val_loss: 1.4677 - val_accuracy: 0.7974
Epoch 26/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0888 - accuracy: 0.9646 - val_loss: 1.5298 - val_accuracy: 0.8010
Epoch 27/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0884 - accuracy: 0.9643 - val_loss: 1.6308 - val_accuracy: 0.7979
Epoch 28/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0887 - accuracy: 0.9639 - val_loss: 1.5564 - val_accuracy: 0.7974
Epoch 29/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0886 - accuracy: 0.9644 - val_loss: 1.5284 - val_accuracy: 0.7999
Epoch 30/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0881 - accuracy: 0.9655 - val_loss: 1.5261 - val_accuracy: 0.7979
Epoch 31/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0876 - accuracy: 0.9646 - val_loss: 1.5643 - val_accuracy: 0.7994
Epoch 32/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0880 - accuracy: 0.9646 - val_loss: 1.4745 - val_accuracy: 0.7966
Epoch 33/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0880 - accuracy: 0.9639 - val_loss: 1.5103 - val_accuracy: 0.7984
Epoch 34/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0989 - accuracy: 0.9632 - val_loss: 0.4780 - val_accuracy: 0.7999
Epoch 35/100
684/684 [==============================] - 2s 3ms/step - loss: 0.1016 - accuracy: 0.9630 - val_loss: 0.6582 - val_accuracy: 0.7989
Epoch 36/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0917 - accuracy: 0.9638 - val_loss: 0.9886 - val_accuracy: 0.8012
Epoch 37/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0874 - accuracy: 0.9646 - val_loss: 1.9287 - val_accuracy: 0.7971
Epoch 38/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0850 - accuracy: 0.9647 - val_loss: 2.6038 - val_accuracy: 0.7994
Epoch 39/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0840 - accuracy: 0.9662 - val_loss: 2.6733 - val_accuracy: 0.7976
Epoch 40/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0843 - accuracy: 0.9651 - val_loss: 2.9471 - val_accuracy: 0.7984
Epoch 41/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0834 - accuracy: 0.9653 - val_loss: 2.9461 - val_accuracy: 0.7997
Epoch 42/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0839 - accuracy: 0.9657 - val_loss: 3.1857 - val_accuracy: 0.7981
Epoch 43/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0830 - accuracy: 0.9657 - val_loss: 2.6365 - val_accuracy: 0.7989
Epoch 44/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0829 - accuracy: 0.9656 - val_loss: 2.8623 - val_accuracy: 0.7948
Epoch 45/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0830 - accuracy: 0.9657 - val_loss: 2.3643 - val_accuracy: 0.7987
Epoch 46/100
684/684 [==============================] - 2s 3ms/step - loss: 0.1021 - accuracy: 0.9585 - val_loss: 3.6319 - val_accuracy: 0.7994
Epoch 47/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0933 - accuracy: 0.9628 - val_loss: 3.1621 - val_accuracy: 0.7994
Epoch 48/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0872 - accuracy: 0.9638 - val_loss: 3.4260 - val_accuracy: 0.7999
Epoch 49/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0849 - accuracy: 0.9646 - val_loss: 2.7472 - val_accuracy: 0.7999
Epoch 50/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0844 - accuracy: 0.9649 - val_loss: 3.1170 - val_accuracy: 0.7976
Epoch 51/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0853 - accuracy: 0.9648 - val_loss: 2.9593 - val_accuracy: 0.7974
Epoch 52/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0844 - accuracy: 0.9646 - val_loss: 2.5849 - val_accuracy: 0.7992
Epoch 53/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0839 - accuracy: 0.9645 - val_loss: 3.1260 - val_accuracy: 0.7984
Epoch 54/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0842 - accuracy: 0.9652 - val_loss: 2.7888 - val_accuracy: 0.7989
Epoch 55/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0837 - accuracy: 0.9652 - val_loss: 2.5350 - val_accuracy: 0.7976
Epoch 56/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0837 - accuracy: 0.9656 - val_loss: 2.2520 - val_accuracy: 0.7984
Epoch 57/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0839 - accuracy: 0.9649 - val_loss: 2.5227 - val_accuracy: 0.7984
Epoch 58/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0834 - accuracy: 0.9655 - val_loss: 2.4278 - val_accuracy: 0.8010
Epoch 59/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0838 - accuracy: 0.9653 - val_loss: 2.1397 - val_accuracy: 0.8007
Epoch 60/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0843 - accuracy: 0.9659 - val_loss: 2.2652 - val_accuracy: 0.8010
Epoch 61/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0831 - accuracy: 0.9658 - val_loss: 2.1744 - val_accuracy: 0.8002
Epoch 62/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0830 - accuracy: 0.9656 - val_loss: 2.9830 - val_accuracy: 0.7989
Epoch 63/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0828 - accuracy: 0.9657 - val_loss: 2.5122 - val_accuracy: 0.8005
Epoch 64/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0825 - accuracy: 0.9658 - val_loss: 3.0330 - val_accuracy: 0.8007
Epoch 65/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0822 - accuracy: 0.9657 - val_loss: 2.6054 - val_accuracy: 0.8005
Epoch 66/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0831 - accuracy: 0.9652 - val_loss: 2.6798 - val_accuracy: 0.7958
Epoch 67/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0819 - accuracy: 0.9658 - val_loss: 2.8876 - val_accuracy: 0.8007
Epoch 68/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0821 - accuracy: 0.9655 - val_loss: 2.5633 - val_accuracy: 0.7994
Epoch 69/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0819 - accuracy: 0.9657 - val_loss: 2.3303 - val_accuracy: 0.8005
Epoch 70/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0818 - accuracy: 0.9656 - val_loss: 1.9681 - val_accuracy: 0.7999
Epoch 71/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0820 - accuracy: 0.9653 - val_loss: 2.1825 - val_accuracy: 0.8007
Epoch 72/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0818 - accuracy: 0.9662 - val_loss: 1.7887 - val_accuracy: 0.8002
Epoch 73/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0815 - accuracy: 0.9661 - val_loss: 1.7347 - val_accuracy: 0.8005
Epoch 74/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0815 - accuracy: 0.9664 - val_loss: 2.0339 - val_accuracy: 0.8002
Epoch 75/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0812 - accuracy: 0.9658 - val_loss: 1.8104 - val_accuracy: 0.8005
Epoch 76/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0814 - accuracy: 0.9661 - val_loss: 1.5176 - val_accuracy: 0.8002
Epoch 77/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0810 - accuracy: 0.9664 - val_loss: 1.7099 - val_accuracy: 0.8005
Epoch 78/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0813 - accuracy: 0.9665 - val_loss: 1.6632 - val_accuracy: 0.8015
Epoch 79/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0813 - accuracy: 0.9660 - val_loss: 1.2540 - val_accuracy: 0.7999
Epoch 80/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0810 - accuracy: 0.9658 - val_loss: 1.9678 - val_accuracy: 0.8002
Epoch 81/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0804 - accuracy: 0.9663 - val_loss: 1.8421 - val_accuracy: 0.8002
Epoch 82/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0808 - accuracy: 0.9669 - val_loss: 1.9266 - val_accuracy: 0.8010
Epoch 83/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0808 - accuracy: 0.9667 - val_loss: 1.8541 - val_accuracy: 0.7989
Epoch 84/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0822 - accuracy: 0.9661 - val_loss: 1.4252 - val_accuracy: 0.8005
Epoch 85/100
684/684 [==============================] - 2s 3ms/step - loss: 0.1740 - accuracy: 0.9360 - val_loss: 1.3398 - val_accuracy: 0.7901
Epoch 86/100
684/684 [==============================] - 2s 3ms/step - loss: 0.1231 - accuracy: 0.9538 - val_loss: 0.8949 - val_accuracy: 0.7893
Epoch 87/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0948 - accuracy: 0.9618 - val_loss: 1.2437 - val_accuracy: 0.7974
Epoch 88/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0888 - accuracy: 0.9630 - val_loss: 1.8824 - val_accuracy: 0.7971
Epoch 89/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0864 - accuracy: 0.9638 - val_loss: 1.7097 - val_accuracy: 0.7971
Epoch 90/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0849 - accuracy: 0.9647 - val_loss: 1.6434 - val_accuracy: 0.7958
Epoch 91/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0835 - accuracy: 0.9653 - val_loss: 2.3378 - val_accuracy: 0.7958
Epoch 92/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0825 - accuracy: 0.9652 - val_loss: 2.7071 - val_accuracy: 0.7976
Epoch 93/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0821 - accuracy: 0.9655 - val_loss: 3.0144 - val_accuracy: 0.7971
Epoch 94/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0819 - accuracy: 0.9654 - val_loss: 2.9957 - val_accuracy: 0.7971
Epoch 95/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0818 - accuracy: 0.9657 - val_loss: 3.0998 - val_accuracy: 0.7968
Epoch 96/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0818 - accuracy: 0.9648 - val_loss: 2.9547 - val_accuracy: 0.7961
Epoch 97/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0815 - accuracy: 0.9658 - val_loss: 2.7946 - val_accuracy: 0.7955
Epoch 98/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0816 - accuracy: 0.9657 - val_loss: 2.1314 - val_accuracy: 0.7961
Epoch 99/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0813 - accuracy: 0.9655 - val_loss: 3.0978 - val_accuracy: 0.7968
Epoch 100/100
684/684 [==============================] - 2s 3ms/step - loss: 0.0811 - accuracy: 0.9660 - val_loss: 2.8788 - val_accuracy: 0.7958

In [20]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.6022 - accuracy: 0.7734 - 356ms/epoch - 1ms/step
Loss: 0.6022396087646484, Accuracy: 0.7734110951423645

In [21]:
# Export model to HDF5 File

from google.colab import files

nn.save('/content/AlphabetSoupCharity_Optimization.h5')
files.download('/content/AlphabetSoupCharity_Optimization.h5')